// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
// The UI theme is named PINK_CAT (pink cat): main color pink, secondary color purple
#include "ui.h"
#include "ui_helpers.h"
#include "ui_ext.h"
#include "ui_disp_item.h"
#include "ui_display_filter.h"
#include "ui_data_entry.h"
#include "ui_theme.h"
#include "theme_engine/theme_interface.h"
#include "app_obd_dsp/app_event.h"
#include <driver/gpio.h>
#include "bsp_obd_dsp/bsp_board.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "bsp_obd_dsp/lcd_driver/ST77916.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "bsp_obd_dsp/espnow_link.h"
#include "bsp_obd_dsp/gauge_pair_ble_client.h"
#include "bsp_obd_dsp/racechrono_ble_diy.h"
#include "app_obd_dsp/vehicle_profiles.h"
#include "app_obd_dsp/boot_block_player.h"
#include "app_obd_dsp/boot_media_mount.h"
#include "app_obd_dsp/ota_wifi_server.h"
#include "esp_system.h"
#include "esp_random.h"
#include "esp_log.h"
#include "esp_idf_version.h"
#include "esp_timer.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ui_status_ring.h"
#include "ui_peak_marker.h"


static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t * ui_ScreenPageLogo;
lv_obj_t * imageLogo;
lv_obj_t * imageEasterEgg;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
lv_obj_t * ui_ScreenPageMain;
lv_obj_t * ui_ImageMainPageback;
lv_obj_t * ui_SpinnerMainPage;
lv_obj_t * ui_ArcGearNumBack;
lv_obj_t * ui_LabelGeningRpmText;
lv_obj_t * ui_LabelGeningRpmUnitText;
lv_obj_t * ui_LabelCarSpeedText;
lv_obj_t * ui_LabelCarSpeedUnitText;
lv_obj_t * ui_ContainerMainPageBottomBlock;
lv_obj_t * ui_LabelGearNumText;
lv_obj_t * ui_ContainerMainPageMlieageBlock;
lv_obj_t * ui_LabelMainMlieageText;
lv_obj_t * ui_LabelMainMieageNum;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageGear
void ui_ScreenPageGear_screen_init(void);
lv_obj_t * ui_ScreenPageGear;
lv_obj_t * ui_SpinnerGearPage;
lv_obj_t * ui_GearPageArcGearNumBack;
lv_obj_t * ui_GearPageArcLabelGearNumText;
lv_obj_t * ui_ImageGearBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageThemeGauge (theme-partition custom gauge page; only
// reachable if the active theme declares a "main_gauge" theme page — see
// theme_engine/theme_interface.h. Not SquareLine-generated, hand-written below.)
void ui_ScreenPageThemeGauge_screen_init(void);
lv_obj_t * ui_ScreenPageThemeGauge;
void ui_event_theme_gauge_background(lv_event_t * e);
uint8_t ui_theme_gauge_page_index = 0;  // Current theme page index

// SCREEN: ui_ScreenPageRpm
void ui_ScreenPageRpm_screen_init(void);
lv_obj_t * ui_ScreenPageRpm;
lv_obj_t * ui_SpinnerRpmPage;
lv_obj_t * ui_RpmPageArcRpmBack;
lv_obj_t * ui_RpmPageArcLabelRpmText;
lv_obj_t * ui_RpmPageArcLabelRpmUnit;
lv_obj_t * ui_ImageRpmBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageSpeed
void ui_ScreenPageSpeed_screen_init(void);
lv_obj_t * ui_ScreenPageSpeed;
lv_obj_t * ui_SpinnerSpeedPage;
lv_obj_t * ui_SpeedPageArcSpeedBack;
lv_obj_t * ui_SpeedPageArcLabelSpeedText;
lv_obj_t * ui_SpeedPageArcLabelSpeedUnit;
lv_obj_t * ui_ImageSpeedBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageEasterEgg
void ui_ScreenPageEasterEgg_screen_init(void);
lv_obj_t * ui_ScreenPageEasterEgg;
lv_obj_t * ui_SpinnerEasterEgg;
lv_obj_t * ArcPageEasterEggBack;
lv_obj_t * ui_ImageEggBlackEar;
lv_obj_t * ui_LabelEasterEggInfo;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
lv_obj_t * ui_ScreenPageBLEScan;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageOTAMode
void ui_ScreenPageOTAMode_screen_init(void);
void ui_ota_mode_refresh(void);

// SCREEN: ui_ScreenPageTemp
void ui_ScreenPageTemp_screen_init(void);
lv_obj_t * ui_ScreenPageTemp;

// SCREEN: ui_ScreenPageTempCustom
void ui_ScreenPageTempCustom_screen_init(void);
lv_obj_t * ui_ScreenPageTempCustom;

// SCREEN: ui_ScreenPageOilPressure
void ui_ScreenPageOilPressure_screen_init(void);
lv_obj_t * ui_ScreenPageOilPressure;

// SCREEN: ui_ScreenPageInfo
void ui_ScreenPageInfo_screen_init(void);
extern lv_obj_t * ui_ScreenPageInfo;

// SCREEN: ui_ScreenPageInfoCustom
void ui_ScreenPageInfoCustom_screen_init(void);
lv_obj_t * ui_ScreenPageInfoCustom;
lv_obj_t * ui_ScreenPageGForce;
lv_obj_t * ui_ScreenPageGForceCal;
lv_obj_t * ui_ScreenPageExpression;
// labels defined in ui_ScreenPageInfo.c
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
lv_obj_t * ui_ScreenPageSettings;
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
lv_obj_t *ui_ScreenPageBasicSettings;
lv_obj_t *ui_ScreenPageOBDConnect;
lv_obj_t *ui_ScreenPageMoreSettings;
#endif
lv_obj_t * ui_ScreenPageFeedback;
lv_obj_t *ui_ScreenPageCxSettings;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageOilWarn
void ui_ScreenPageOilWarn_screen_init(void);
lv_obj_t * ui_ScreenPageOilWarn;
void ui_ScreenPageRpmWarn_screen_init(void);
lv_obj_t * ui_ScreenPageRpmWarn;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageNeedle (needle-style configurable gauge)
void ui_ScreenPageNeedle_screen_init(void);
lv_obj_t * ui_ScreenPageNeedle;
lv_meter_scale_t * ui_NeedleScale;
lv_meter_indicator_t * ui_NeedleIndic;
lv_obj_t * ui_NeedleMeter;
lv_obj_t * ui_NeedleValueLabel;
lv_obj_t * ui_NeedleNameLabel;
lv_obj_t * ui_NeedleUnitLabel;
// SCREEN: ui_ScreenPageNeedleConfig
void ui_ScreenPageNeedleConfig_screen_init(void);
lv_obj_t * ui_ScreenPageNeedleConfig;

// SCREEN: ui_ScreenPageMultiGauge (triple-gauge settings: master/slave + master selection)
void ui_ScreenPageMultiGauge_screen_init(void);
lv_obj_t * ui_ScreenPageMultiGauge;

// SCREEN: ui_ScreenPageChartConfig (chart data-source selection)
void ui_ScreenPageChartConfig_screen_init(void);
lv_obj_t * ui_ScreenPageChartConfig;

// SCREEN: ui_ScreenPageChartAlarm (chart alarm threshold settings)
void ui_ScreenPageChartAlarm_screen_init(void);
lv_obj_t * ui_ScreenPageChartAlarm;

// SCREEN: ui_ScreenPageIntro (triple-gauge boot animation RACE/AS/ONE)
void ui_ScreenPageIntro_screen_init(void);
lv_obj_t * ui_ScreenPageIntro;

// SCREEN: ui_ScreenPageODBProtocal
void ui_ScreenPageODBProtocal_screen_init(void);
lv_obj_t * ui_ScreenPageODBProtocal;
lv_obj_t * ui_SpinnerODBProtocalEgg;
lv_obj_t * ui_ArcPageODBProtocalBack;
lv_obj_t * ui_RollerODBProtocalChoose;
lv_obj_t * ui_ImageODBProtocalBlackEar;
lv_obj_t * ui_LabelOBDIIText;
lv_obj_t * ui_LabelSureTipText;

// EVENTS
lv_obj_t * ui____initial_actions0;


static uint16_t usSaveProtTimeCnt = 0; //OBD protocol save timer

// IMAGES AND IMAGE SETS
#define SAVE_PROTOCOL_TIME 2000 //long-press duration to save the protocol, ms
 
///////////////////// TEST LVGL SETTINGS ////////////////////
/* ---- Gauge sweep animation ----
   Moved to ui_ext.c; the SWEEP_* constants live in ui_ext.h and the sweep state
   machine is driven via ui_ext_sweep_active()/ui_ext_sweep_get_step()/ui_ext_sweep_tick(). */
#define OIL_PRESS_TREND_POINTS 30
#define OIL_PRESS_TREND_SAMPLE_MS 1000

/* ---- Digit-ramp animation thresholds (used by disp_item_update) ---- */
#define ANIM_THRESH_RPM   50   // RPM diff ≤50 steps by ±1
#define ANIM_THRESH_SPD   10   // speed diff ≤10 steps by ±1
#define ANIM_THRESH_TEMP   5   // temperature diff ≤5 steps by ±1

// Adaptive step: diff ≤ threshold steps by ±1, diff > threshold approaches proportionally
// The RPM/Speed pages must update label + arc together, which differs from disp_item_update, so a local copy is kept
static inline int32_t anim_step_i32(int32_t displayed, int32_t target, int32_t threshold)
{
    int32_t diff = target - displayed;
    if (diff == 0) return displayed;
    int32_t abs_diff = (diff > 0) ? diff : -diff;
    int32_t step = (diff > 0) ? 1 : -1;

    if (abs_diff > threshold) {
        int32_t rapid = abs_diff / 2;     // eat ~50% of the gap per tick (was 33%, faster convergence)
        if (rapid < 2) rapid = 2;          // minimum 2 steps
        if (rapid > abs_diff) rapid = abs_diff;
        step = (diff > 0) ? rapid : -rapid;
    }
    return displayed + step;
}

// RPM warning flash (test ticks, strobe, linked ramp) migrated to ui_ext.c — see ui_ext_rpm_flash_tick()

// LVGL task handle (set by app_main); priority is temporarily raised to own the CPU while flashing
TaskHandle_t g_lvgl_task_handle = NULL;

// ===== Showroom mode / boot-video state =====
// Moved to ui_ext.c (see ui_ext_showroom_* / ui_ext_boot_video_tick / ui_ext_intro_tick).

// (showroom_load_slot / boot_video_timer_cb moved to ui_ext.c)

// (ui_sweep_get_step / ui_showroom_* / ui_intro_* accessors moved to ui_ext.c)
static int16_t s_oil_pressure_trend[OIL_PRESS_TREND_POINTS];
static bool s_oil_pressure_trend_ready = false;
static uint32_t s_oil_pressure_trend_tick = 0;
// Generic chart page: invalid-sample sentinel (distinct from legit negative values like coolant temp -10) + raw-value range of the current data item (clamping/Y-axis on refresh)
// CHART_INVALID has moved to ui_disp_item.h
static int32_t s_chart_ymin = 0;
static int32_t s_chart_ymax = 100;

// The disp_item system has moved to ui_disp_item.c/h

static uint8_t needle_active_source(void)
{
    uint8_t src = nvs_cfg_get()->needle_source_idx;
    if (src >= DISP_ITEM_COUNT) src = DISP_ITEM_CLT;
    return src;
}

void ui_needle_apply_source(void)
{
    if (!ui_NeedleMeter || !ui_NeedleScale) return;
    uint8_t src = needle_active_source();
    const needle_scale_meta_t *ns = ui_disp_item_scale(src);
    // 270° sweep, start angle 135° (gap centered at the bottom), matching classic mechanical gauges
    lv_meter_set_scale_range(ui_NeedleMeter, ui_NeedleScale, ns->nmin * ns->div, ns->nmax * ns->div, 270, 135);
    lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, ns->nmin * ns->div);
    if (ui_NeedleNameLabel) lv_label_set_text(ui_NeedleNameLabel, s_disp_meta[src].name);
    if (ui_NeedleUnitLabel) lv_label_set_text(ui_NeedleUnitLabel, s_disp_meta[src].unit);
}

void ui_needle_page_update(float sweep_ratio, int16_t clt, int16_t iat, int16_t oil,
                           int16_t load_pct, int16_t tps, int32_t bat_mv,
                           int16_t oilp_x10, int16_t brake_x10,
                           uint16_t rpm, uint16_t speed, int16_t boost_x10,
                           int16_t afr_x100)
{
    if (!ui_ScreenPageNeedle || !ui_NeedleMeter || !ui_NeedleIndic) return;
    uint8_t src = needle_active_source();
    const needle_scale_meta_t *ns = ui_disp_item_scale(src);
    int32_t minimum = ns->nmin * ns->div;
    int32_t maximum = ns->nmax * ns->div;
    static int32_t s_last_needle_meter = INT32_MIN;

    // Sweep self-test after connecting: the needle sweeps the full range nmin→nmax→nmin
    if (sweep_ratio >= 0.0f) {
        if (sweep_ratio > 1.0f) sweep_ratio = 1.0f;
        int32_t nval = minimum + (int32_t)((float)(maximum - minimum) * sweep_ratio);
        if (nval != s_last_needle_meter) {
            lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, nval);
            s_last_needle_meter = nval;
        }
        disp_item_set_text(ui_NeedleValueLabel, src, nval, true);
        return;
    }

    int32_t raw = 0;
    bool valid = disp_item_read_value(src, clt, iat, oil, load_pct, tps, bat_mv,
                                      oilp_x10, brake_x10, rpm, speed, boost_x10, afr_x100, &raw);

    static int32_t s_disp_needle = 0;
    static uint8_t s_last_needle_src = 0xFF;
    if (s_last_needle_src != src) {
        s_last_needle_src = src;
        s_disp_needle = 0;  // reset on source switch, avoiding a ramp from the old source's value
    }
    /* Threshold = 3% of range: small ranges (temps) smooth by ±1, large ranges (RPM) approach proportionally */
    int32_t needle_thresh = (maximum - minimum) / 30;
    if (needle_thresh < 2) needle_thresh = 2;

    if (valid && ui_data_entry_pending(ui_ScreenPageNeedle)) s_disp_needle = raw;
    disp_item_update(&s_disp_needle, ui_NeedleValueLabel, src, raw, valid, needle_thresh);

    // Needle position: use the smoothed value
    int32_t nval = valid ? s_disp_needle : minimum;
    if (nval < minimum) nval = minimum;
    if (nval > maximum) nval = maximum;
    if (ui_data_entry_pending(ui_ScreenPageNeedle) || nval != s_last_needle_meter) {
        lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, nval);
        s_last_needle_meter = nval;
    }
}

static void oil_pressure_trend_init(void)
{
    if (s_oil_pressure_trend_ready) return;

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS; ++i) {
        s_oil_pressure_trend[i] = CHART_INVALID;
    }

    s_oil_pressure_trend_ready = true;
}

static void oil_pressure_trend_push(int16_t sample_x10)
{
    oil_pressure_trend_init();

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS - 1; ++i) {
        s_oil_pressure_trend[i] = s_oil_pressure_trend[i + 1];
    }
    s_oil_pressure_trend[OIL_PRESS_TREND_POINTS - 1] = sample_x10;
}

// Generic chart refresh: Y range = s_chart_ymin..s_chart_ymax (set per data item by ui_chart_apply_source);
// invalid samples (CHART_INVALID) keep the last valid value; legit negative values (e.g. coolant temp) are supported.
static void oil_pressure_chart_refresh(void)
{
    if (!ui_ChartOilPressure || !ui_OilPressureChartSeries) return;

    int32_t last_valid = s_chart_ymin;
    bool has_last = false;

    lv_chart_set_range(ui_ChartOilPressure, LV_CHART_AXIS_PRIMARY_Y, s_chart_ymin, s_chart_ymax);

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS; ++i) {
        int16_t sample = s_oil_pressure_trend[i];
        int32_t v;

        if (sample != CHART_INVALID) {
            last_valid = sample;
            has_last = true;
        }

        v = has_last ? last_valid : s_chart_ymin;
        if (v < s_chart_ymin) v = s_chart_ymin;
        if (v > s_chart_ymax) v = s_chart_ymax;

        lv_chart_set_value_by_id(ui_ChartOilPressure, ui_OilPressureChartSeries, i, v);
    }

    lv_chart_refresh(ui_ChartOilPressure);
}

// Apply the chart page title/dot/unit/color/Y-range per chart_source_idx (call after the data source changes)
void ui_chart_apply_source(void)
{
    uint8_t src = nvs_cfg_get()->chart_source_idx;
    if (src >= DISP_ITEM_COUNT) src = DISP_ITEM_OILP;
    const disp_item_meta_t *m = &s_disp_meta[src];
    const needle_scale_meta_t *ns = ui_disp_item_scale(src);
    s_chart_ymin = ns->nmin * ns->div;   // raw-value range (matches the raw values fed to the chart)
    s_chart_ymax = ns->nmax * ns->div;
    if (ui_LabelChartTitle) {
        lv_label_set_text(ui_LabelChartTitle, m->name);
        lv_obj_set_style_text_color(ui_LabelChartTitle, lv_color_hex(m->color), LV_PART_MAIN);
    }
    if (ui_ChartDot) lv_obj_set_style_bg_color(ui_ChartDot, lv_color_hex(m->color), LV_PART_MAIN);
    if (ui_LabelChartUnit) lv_label_set_text(ui_LabelChartUnit, m->unit);
    if (ui_ChartOilPressure) {
        lv_obj_set_style_line_color(ui_ChartOilPressure, lv_color_hex(m->color), LV_PART_ITEMS);
        // the line actually uses the series' own color (overrides the ITEMS style); the series color must be changed directly for it to take effect
        if (ui_OilPressureChartSeries) ui_OilPressureChartSeries->color = lv_color_hex(m->color);
        lv_chart_set_range(ui_ChartOilPressure, LV_CHART_AXIS_PRIMARY_Y, s_chart_ymin, s_chart_ymax);
        lv_chart_refresh(ui_ChartOilPressure);
    }
    // reset the trend buffer so no stale curve remains after switching data source
    s_oil_pressure_trend_ready = false;
    s_oil_pressure_trend_tick = 0;
}

// ===== Boot flow state / "NO SIGNAL" overlay =====
// (boot_goto_ble_scan / boot_enter_default_page / update_no_signal_overlay moved to ui_ext.c)

static void ui_update_metric_header(lv_obj_t *name_label,
                                    lv_obj_t *unit_label,
                                    lv_obj_t *dot_label,
                                    disp_item_t item)
{
    lv_color_t color = lv_color_hex(s_disp_meta[item].color);

    if (name_label) {
        lv_label_set_text(name_label, s_disp_meta[item].name);
        lv_obj_set_style_text_color(name_label, color, LV_PART_MAIN);
    }
    if (unit_label) {
        lv_label_set_text(unit_label, s_disp_meta[item].unit);
    }
    if (dot_label) {
        lv_obj_set_style_bg_color(dot_label, color, LV_PART_MAIN);
    }
}

static uint32_t ui_refresh_period_ms_for_screen(lv_obj_t *scr,
                                                bool in_sweep,
                                                bool rpm_flashing,
                                                bool rpm_link_ramp)
{
    if (in_sweep) {
        return SWEEP_TICK_MS;
    }
    if (rpm_flashing) {
        return RPM_FLASH_PERIOD_MS;
    }
    if (rpm_link_ramp) {
        return 16;
    }

    if (scr == ui_ScreenPageGear || scr == ui_ScreenPageRpm ||
        scr == ui_ScreenPageSpeed || scr == ui_ScreenPageNeedle ||
        scr == ui_ScreenPageThemeGauge) {
        return 16;
    }
    if (scr == ui_ScreenPageTemp || scr == ui_ScreenPageInfo ||
        scr == ui_ScreenPageOilPressure || scr == ui_ScreenPageLogo ||
        scr == ui_ScreenPageIntro) {
        return 33;
    }
    if (
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
        scr == ui_ScreenPageBasicSettings || scr == ui_ScreenPageOBDConnect ||
        scr == ui_ScreenPageMoreSettings || scr == ui_ScreenPageFeedback || scr == ui_ScreenPageCxSettings ||
        scr == ui_ScreenPageRingSettings ||
#endif
        scr == ui_ScreenPageSettings || scr == ui_ScreenPageMultiGauge ||
        scr == ui_ScreenPageBLEScan || scr == ui_ScreenPageOTAMode || scr == ui_ScreenPageODBProtocal ||
        scr == ui_ScreenPageTempCustom || scr == ui_ScreenPageInfoCustom ||
        scr == ui_ScreenPageNeedleConfig || scr == ui_ScreenPageChartConfig ||
        scr == ui_ScreenPageChartAlarm || scr == ui_ScreenPageOilWarn ||
        scr == ui_ScreenPageRpmWarn || scr == ui_ScreenPageEasterEgg) {
        return 200;
    }
    return 50;
}

static bool ui_screen_updates_live_data(lv_obj_t *scr)
{
    return scr == ui_ScreenPageGear || scr == ui_ScreenPageRpm ||
           scr == ui_ScreenPageSpeed || scr == ui_ScreenPageNeedle ||
           scr == ui_ScreenPageTemp || scr == ui_ScreenPageOilPressure ||
           scr == ui_ScreenPageInfo || scr == ui_ScreenPageThemeGauge;
}

// Converts the core firmware's live OBD snapshot into the ABI-stable struct
// theme_engine consumes, applying the unit conversions the two structs don't
// share (boost 0.1bar->0.01bar, oil pressure bar->PSI, battery mV->0.1V) and
// clamping into the narrower target field widths. Invalid-sentinel fields are
// passed through as 0 rather than propagating e.g. -32768 into a uint8_t.
static void ui_build_theme_snapshot(obd_snapshot_t *out,
                                     int16_t clt, int16_t oil, int16_t oilp_x10,
                                     int32_t bat_mv, int16_t boost_x10, int16_t afr_x100,
                                     uint16_t usRpm, uint16_t ucSpeed, int16_t tps,
                                     enGear eGear, bool gear_unknown)
{
    memset(out, 0, sizeof(*out));
    out->rpm = usRpm == UINT16_MAX ? 0 : usRpm;
    out->speed = ucSpeed == UINT16_MAX ? 0 : (ucSpeed > 255 ? 255 : (uint8_t)ucSpeed);
    out->boost = (boost_x10 <= -32768) ? 0 : (int16_t)(boost_x10 * 10);
    out->coolant_temp = (clt < 0) ? 0 : (clt > 255 ? 255 : (uint8_t)clt);
    if (oilp_x10 < 0) {
        out->oil_pressure = 0;
    } else {
        int32_t psi = (int32_t)(oilp_x10 * 1.45038f / 10.0f + 0.5f);
        out->oil_pressure = (psi > 255) ? 255 : (uint8_t)psi;
    }
    out->gear = gear_unknown ? (int8_t)127 : (int8_t)eGear;
    if (bat_mv < 0) {
        out->battery_voltage = 0;
    } else {
        int32_t dv = bat_mv / 100;
        out->battery_voltage = (dv > 255) ? 255 : (uint8_t)dv;
    }
    out->oil_temp = (oil < 0) ? 0 : (oil > 255 ? 255 : (uint8_t)oil);
    out->afr = (afr_x100 < 0) ? 0 : (uint16_t)afr_x100;
    out->throttle = (tps < 0) ? 0 : (tps > 100 ? 100 : (uint8_t)tps);
}

void my_timerMain(lv_timer_t * timer)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    ui_cx_power_update();
    ui_status_ring_tick();
    ui_peak_marker_tick();
    ui_settings_refresh();
#endif
    // ---- Process the event queue (ESP-NOW / BLE cross-task events) ----
    {
        app_event_t evt;
        while (app_event_recv(&evt)) {
            switch (evt.type) {
                case APP_EVT_ESPNOW_SYNC_SLOT:
                    ui_showroom_set_page_from_sync((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_INTRO_STEP:
                    ui_intro_set_step((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_ENTER_SHOWROOM:
                    ui_showroom_set_active(true);
                    break;
                case APP_EVT_ESPNOW_THRESH_SYNC:
                    // RPM threshold synced from another gauge: write local NVS (the master forwards it to the other slaves) + refresh this page
                    espnow_link_apply_synced_threshold((uint16_t)evt.data.u16);
                    ui_rpm_warn_refresh_from_nvs();
                    break;
                default:
                    break;
            }
        }
    }

    static uint16_t usRpm = 0;
    static uint16_t ucSpeed = 0;  // uint16_t so sweep can reach 999
    uint16_t rpm_for_warning = usRpm;
    static enGear eGear = GEAR_NEUTRAL;
    static bool  s_gear_unknown = false;   // OBD-gear profile can't read a valid gear → show "--" (no ratio-calc fallback)
    // rpm flash state (red/black toggle, strobing flag, linked ramp) moved to ui_ext.c
    // Sweep animation detection (excludes showroom sync values 200+); sweep state lives in ui_ext.c now
    #define IN_SWEEP (ui_ext_sweep_active())
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;

    const nvs_user_cfg_t *user_cfg = nvs_cfg_get();
    int16_t clt = 0;
    int16_t iat = 0;
    int16_t oil = 0;
    int16_t oilp_x10 = 0;
    int16_t brake_x10 = 0;
    int16_t load_pct = 0;
    int16_t tps = 0;
    int32_t bat_mv = 0;
    int16_t boost_x10 = 0;
    int16_t afr_x100 = 0;

    /* ---- Sweep trigger ----
       Master: triggered the instant the ELM327 BLE connects and advances the animation itself;
       Slave: never self-triggers, driven by the master's broadcast sweep_step (espnow recv → app_event queue). */
    bool is_slave = (user_cfg->device_role == ESPNOW_ROLE_SLAVE);
    // "connected" signal: slave=master data being received, master=ELM327 BLE connected (shared by status display and the master's sweep trigger)
    bool ble_now = is_slave ? espnow_link_slave_has_data() : elm327_ble_is_connected();
    ui_ext_sweep_trigger(ble_now, is_slave);
    /* ---- Showroom mode: master drives slots, slaves follow (moved to ui_ext.c) ---- */
    ui_ext_showroom_tick(is_slave);

    lv_obj_t *scr = lv_scr_act();
    bool live_data_screen = ui_screen_updates_live_data(scr);
    const bool on_entry = ui_data_entry_pending(scr);
    bool rpm_warn_possible = ui_ext_rpm_warn_possible();

    if (IN_SWEEP || (!ble_now && !ui_ext_showroom_is_active())) {
        ui_display_filter_reset();
    }

    if (!IN_SWEEP && (live_data_screen || rpm_warn_possible || ui_ext_rpm_is_flashing() || ui_ext_rpm_link_ramp_active())) {
        obd_data_snapshot_t obd;
        obd_data_snapshot_t display;
        obd_data_freshness_t freshness;

        obd_data_get_fresh_snapshot(&obd, &freshness);
        bool demo = ui_ext_showroom_is_active();
        if (!demo) {
            if (!ble_now) memset(&freshness, 0xff, sizeof(freshness));
            obd_data_apply_freshness(&obd, &freshness);
        }
        bool rpm_valid = demo || obd_data_sample_is_fresh(&freshness, OBD_SAMPLE_RPM);
        bool speed_valid = demo || obd_data_sample_is_fresh(&freshness, OBD_SAMPLE_SPEED);
        rpm_for_warning = obd.rpm;
        ui_display_filter_apply(&obd, &display, lv_tick_get());
        clt       = display.coolant_temp;
        iat       = display.intake_temp;
        oil       = display.oil_temp;      // real oil temperature °C (SSM 22 10 17), -100=invalid
        oilp_x10  = display.oil_pressure_x10; // oil pressure 0.1bar, -1=invalid
        brake_x10 = display.brake_temp_x10; // brake temperature 0.1°C
        load_pct  = display.load_pct;      // engine load 0~100%, -1=invalid
        tps       = display.tps;
        bat_mv    = display.bat_mv;
        boost_x10 = display.boost_x10; // boost gauge pressure 0.1bar, -32768=invalid
        afr_x100  = display.afr_x100;   // air-fuel ratio ×100, -1=invalid
        usRpm     = rpm_valid ? display.rpm : UINT16_MAX;
        ucSpeed   = speed_valid ? display.speed : UINT16_MAX;
        int8_t decoded_gear = obd.gear;
        if (!rpm_valid || !speed_valid) {
            s_gear_unknown = true;
            obd_data_reset_gear_estimate();
        } else if (decoded_gear >= 0 && decoded_gear <= GEAR_8) {
            eGear = (enGear)decoded_gear;
            s_gear_unknown = false;
        } else if (vehicle_profile_get_active()->obd_gear_did != 0) {
            // OBD gear profile: no RPM/speed ratio fallback — show "--" until a valid gear arrives
            s_gear_unknown = true;
        } else {
            eGear = calculate_gear(obd.rpm, obd.speed_unsmoothed);
            s_gear_unknown = eGear == GEAR_UNKNOWN;
        }
    }

    /* ---- Data source: sweep or real OBD (sweep state machine moved to ui_ext.c) ---- */
    float sweep_ratio = ui_ext_sweep_tick(is_slave, user_cfg->brightness_day);
    if (sweep_ratio >= 0.0f) {
        usRpm   = (uint16_t)disp_item_sweep_value(DISP_ITEM_RPM, sweep_ratio);
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
        ucSpeed = (uint16_t)disp_item_sweep_value(DISP_ITEM_SPEED, sweep_ratio);
#else
        ucSpeed = (uint16_t)(SWEEP_SPEED_PEAK * sweep_ratio);
#endif
        eGear   = (enGear)((int)(6.0f * sweep_ratio + 0.5f)); // up to 6th gear
        s_gear_unknown = false;
        // Temp/Info/Chart pages animate their own data item via disp_item_sweep_value();
        // the theme-gauge page (ui_build_theme_snapshot below) has no such per-item logic
        // and just forwards these locals as-is, so without this they'd stay frozen at the
        // 0 they were declared with above (real OBD reads are skipped while IN_SWEEP).
        clt       = (int16_t)disp_item_sweep_value(DISP_ITEM_CLT, sweep_ratio);
        oil       = (int16_t)disp_item_sweep_value(DISP_ITEM_OIL, sweep_ratio);
        oilp_x10  = (int16_t)disp_item_sweep_value(DISP_ITEM_OILP, sweep_ratio);
        bat_mv    = disp_item_sweep_value(DISP_ITEM_BAT, sweep_ratio);
        boost_x10 = (int16_t)disp_item_sweep_value(DISP_ITEM_BOOST, sweep_ratio);
        afr_x100  = (int16_t)disp_item_sweep_value(DISP_ITEM_AFR, sweep_ratio);
        tps       = (int16_t)disp_item_sweep_value(DISP_ITEM_TPS, sweep_ratio);
    }
    /*Gear page: refresh only while this page is actually shown, no idle background updates*/
    if (scr == ui_ScreenPageGear) {
        static const char *pGearNum[] = {"N","1","2","3","4","5","6","7","8"};
        static enGear s_last_gear_disp = GEAR_NEUTRAL;
        static bool s_last_gear_unknown = false;
        uint8_t gc = vehicle_profile_get_active()->gear_count;
        if (gc < 1) gc = 6;
        enGear g = (eGear <= GEAR_8) ? eGear : GEAR_8;
        if (on_entry || s_gear_unknown != s_last_gear_unknown || g != s_last_gear_disp || IN_SWEEP) {
            s_last_gear_unknown = s_gear_unknown;
            s_last_gear_disp = g;
            if (s_gear_unknown) {
                lv_label_set_text(ui_GearPageArcLabelGearNumText, "--");
                lv_arc_set_value(ui_GearPageArcGearNumBack, 0);
            } else {
                lv_label_set_text(ui_GearPageArcLabelGearNumText, pGearNum[g]);
                lv_arc_set_value(ui_GearPageArcGearNumBack, (uint16_t)g * 100 / gc);
            }
        }
    }
    /* Theme-provided gauge page: feed the theme engine's arc/bar/label bindings */
    if (scr == ui_ScreenPageThemeGauge) {
        obd_snapshot_t theme_snap;
        ui_build_theme_snapshot(&theme_snap, clt, oil, oilp_x10, bat_mv, boost_x10, afr_x100,
                                 usRpm, ucSpeed, tps, eGear, s_gear_unknown);
        theme_update_data(&theme_snap);
    }
    /*RPM page: the shared display filter handles jitter; keep the digits and arc in sync.*/
    if (scr == ui_ScreenPageRpm) {
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
        ui_peak_marker_sample(UI_PEAK_RPM, usRpm);
#endif
        static int32_t s_last_rpm = -1;
        if (on_entry || (int32_t)usRpm != s_last_rpm) {
            s_last_rpm = (int32_t)usRpm;
            if (usRpm == UINT16_MAX) {
                lv_label_set_text(ui_RpmPageArcLabelRpmText, "--");
                lv_arc_set_value(ui_RpmPageArcRpmBack, 0);
            } else {
                lv_label_set_text_fmt(ui_RpmPageArcLabelRpmText, "%d", (int)usRpm);
                lv_arc_set_value(ui_RpmPageArcRpmBack, ui_disp_item_arc_percent(DISP_ITEM_RPM, usRpm));
            }
        }
    }
    /*Speed page: same as above, refresh only while the page is active*/
    if (scr == ui_ScreenPageSpeed) {
        static int32_t s_disp_spd = 0;
        static int32_t s_last_spd = -1;
        bool speed_valid = ucSpeed != UINT16_MAX;
        if (!speed_valid) { s_disp_spd = 0; }
        else if (IN_SWEEP || on_entry || strcmp(lv_label_get_text(ui_SpeedPageArcLabelSpeedText), "--") == 0) { s_disp_spd = ucSpeed; }
        else { s_disp_spd = anim_step_i32(s_disp_spd, (int32_t)ucSpeed, ANIM_THRESH_SPD); }
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
        ui_peak_marker_sample(UI_PEAK_SPEED, s_disp_spd);
#endif
        int32_t speed_key = speed_valid ? s_disp_spd : -2;
        if (on_entry || speed_key != s_last_spd) {
            s_last_spd = speed_key;
            if (!speed_valid) lv_label_set_text(ui_SpeedPageArcLabelSpeedText, "--");
            else lv_label_set_text_fmt(ui_SpeedPageArcLabelSpeedText, "%d", (int)s_disp_spd);
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
            lv_arc_set_value(ui_SpeedPageArcSpeedBack, ui_disp_item_arc_percent(DISP_ITEM_SPEED, s_disp_spd));
#else
            lv_arc_set_value(ui_SpeedPageArcSpeedBack, (uint32_t)s_disp_spd*100/SWEEP_SPEED_PEAK);
#endif
        }
    }

 /*Needle page (configurable data source, sweeps along during gauge sweep)*/
    if (scr == ui_ScreenPageNeedle) {
        ui_needle_page_update(sweep_ratio, clt, iat, oil, load_pct, tps, bat_mv,
                              oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100);
    }

    /*Temp page*/
    if (scr == ui_ScreenPageTemp && ui_LabelTempValue[0]) {
        static int32_t s_disp_temp[3] = {0};
        static uint8_t s_last_temp_map[3] = {0xFF, 0xFF, 0xFF};

        if(IN_SWEEP) {
            int step = ui_ext_sweep_get_step() - 1; // already incremented
            float r;
            if(step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // hold at max (hold phase)

            for (int i = 0; i < 3; ++i) {
                uint8_t map_idx = user_cfg->temp_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_temp_map[i] != map_idx) {
                    s_last_temp_map[i] = map_idx;
                    s_disp_temp[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelTempName[i], ui_LabelTempUnit[i], ui_LabelTempDot[i], item);
                }

                int32_t sw = disp_item_sweep_value(item, r);
                disp_item_set_text(ui_LabelTempValue[i], item, sw, true);
                disp_item_set_value_color(ui_LabelTempValue[i], item, sw, true);
            }
        } else {
            for (int i = 0; i < 3; ++i) {
                uint8_t map_idx = user_cfg->temp_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_temp_map[i] != map_idx) {
                    s_last_temp_map[i] = map_idx;
                    s_disp_temp[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelTempName[i], ui_LabelTempUnit[i], ui_LabelTempDot[i], item);
                }

                int32_t value = 0;
                bool valid = disp_item_read_value(item, clt, iat, oil, load_pct, tps, bat_mv, oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100, &value);
                if (on_entry && valid) s_disp_temp[i] = value;
                disp_item_update(&s_disp_temp[i], ui_LabelTempValue[i], item, value, valid, ANIM_THRESH_TEMP);
            }
        }
    }

    /* Generic chart page update: the displayed data item is chosen by chart_source_idx (merges the former oil-pressure/brake-temp pages) */
    if (scr == ui_ScreenPageOilPressure && ui_LabelOilPressureText) {
        static int32_t s_disp_chart = 0;
        static uint8_t s_last_chart_src = 0xFF;
        disp_item_t citem = (disp_item_t)(user_cfg->chart_source_idx % DISP_ITEM_COUNT);
        if (s_last_chart_src != user_cfg->chart_source_idx) {
            s_last_chart_src = user_cfg->chart_source_idx;
            s_disp_chart = 0;  // reset on source switch, avoiding a ramp from the old source's value
        }
        int32_t cval = 0;
        bool cvalid;
        if (IN_SWEEP) {
            int step = ui_ext_sweep_get_step() - 1;
            float r;
            if (step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // hold at max (hold phase)
            cval = disp_item_sweep_value(citem, r);
            cvalid = true;
            s_disp_chart = cval;
            disp_item_set_text(ui_LabelOilPressureText, citem, s_disp_chart, cvalid);
            disp_item_set_value_color(ui_LabelOilPressureText, citem, s_disp_chart, cvalid);
        } else {
            cvalid = disp_item_read_value(citem, clt, iat, oil, load_pct, tps, bat_mv,
                                          oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100, &cval);
            if (on_entry && cvalid) s_disp_chart = cval;
            disp_item_update(&s_disp_chart, ui_LabelOilPressureText, citem, cval, cvalid, ANIM_THRESH_TEMP);
        }

        // Feed the chart and refresh only when not sweeping: during the boot sweep the chart stays put (the sweep is for needles/digits; the trend chart does not take part)
        if (!IN_SWEEP) {
            uint32_t now = lv_tick_get();
            if (s_oil_pressure_trend_tick == 0) {
                oil_pressure_trend_init();
                s_oil_pressure_trend_tick = now;
            }
            bool trend_updated = false;
            while ((now - s_oil_pressure_trend_tick) >= OIL_PRESS_TREND_SAMPLE_MS) {
                oil_pressure_trend_push(cvalid ? (int16_t)s_disp_chart : CHART_INVALID);
                s_oil_pressure_trend_tick += OIL_PRESS_TREND_SAMPLE_MS;
                trend_updated = true;
            }
            // the trend buffer only changes on an actual sample (~once per second), so no need to redraw the whole chart every timer tick
            if (trend_updated) oil_pressure_chart_refresh();
        }
    }

    /* Info page update */
    if (scr == ui_ScreenPageInfo && ui_LabelInfoValue[0]) {
        static int32_t s_disp_info[5] = {0};
        static uint8_t s_last_info_map[5] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF};

        if (IN_SWEEP) {
            int step = ui_ext_sweep_get_step() - 1; // already incremented above
            float r;
            if (step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // hold at max (hold phase)

            for (int i = 0; i < 5; ++i) {
                uint8_t map_idx = user_cfg->info_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_info_map[i] != map_idx) {
                    s_last_info_map[i] = map_idx;
                    s_disp_info[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelInfoName[i], ui_LabelInfoUnit[i], NULL, item);
                }

                int32_t sw = disp_item_sweep_value(item, r);
                disp_item_set_text(ui_LabelInfoValue[i], item, sw, true);
                disp_item_set_value_color(ui_LabelInfoValue[i], item, sw, true);
            }
        } else {
            for (int i = 0; i < 5; ++i) {
                uint8_t map_idx = user_cfg->info_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_info_map[i] != map_idx) {
                    s_last_info_map[i] = map_idx;
                    s_disp_info[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelInfoName[i], ui_LabelInfoUnit[i], NULL, item);
                }

                int32_t value = 0;
                bool valid = disp_item_read_value(item, clt, iat, oil, load_pct, tps, bat_mv, oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100, &value);
                if (on_entry && valid) s_disp_info[i] = value;
                disp_item_update(&s_disp_info[i], ui_LabelInfoValue[i], item, value, valid, ANIM_THRESH_TEMP);
            }
        }
    }

    ui_data_entry_complete(scr);

    /* Dynamically update the EasterEgg (device info) page: role + OBD link state + build tag. */
    if (scr == ui_ScreenPageEasterEgg && ui_LabelEasterEggInfo) {
        static char s_last_easteregg_info[256];
        char info_text[256];
        const char *mode_str = is_slave ? "SLAVE"
                             : (user_cfg->device_role == ESPNOW_ROLE_MASTER) ? "MASTER" : "STANDALONE";
        const char *conn_label, *conn_name;

        if (is_slave) {
            const char *mname = espnow_link_get_master_name();
            conn_label = "SLAVE";
            conn_name  = (ble_now && mname[0]) ? obd_project_display_master_name(mname) : "--";
        } else {
            const char *dev_name = elm327_ble_get_connected_name();
            if(!dev_name || dev_name[0] == '\0') dev_name = "Not set";
            conn_label = "BLE";
            conn_name  = dev_name;
        }

        snprintf(info_text, sizeof(info_text),
            "MODE: %s\n"
            "%s: %s\n"
            "Status: %s\n"
            "BUILD %s\n" OBD_PROJECT_CREDITS,
            mode_str, conn_label, conn_name,
            ble_now ? (is_slave ? "Linked" : "Connected")
                    : (is_slave ? "Waiting" : "Disconnected"),
            OBD_GAUGE_BUILD_TAG);
        if (strcmp(s_last_easteregg_info, info_text) != 0) {
            strncpy(s_last_easteregg_info, info_text, sizeof(s_last_easteregg_info));
            s_last_easteregg_info[sizeof(s_last_easteregg_info) - 1] = '\0';
            lv_label_set_text(ui_LabelEasterEggInfo, s_last_easteregg_info);
        }
    }

    /* OTA mode screen: refresh connection status */
    ui_ota_mode_refresh();

#if EXAMPLE_PIN_NUM_BK_LIGHT >= 0
        //wait 500ms before turning on the backlight, so it isn't enabled before init completes; runs once
        if(ucOnlyOnce == 0)
        {
            ulOpenLightTimeCnt++;
            if(ulOpenLightTimeCnt > 400 / 200)
            {
                uint8_t bright = user_cfg->brightness_day;
                if(bright < 10) bright = 100;
                Set_Backlight(bright);
                ESP_LOGD(TAG, "Set LCD backlight to %d%%", bright);
                ulOpenLightTimeCnt = 0;
                ucOnlyOnce = 1;//run once only
            }
        }
#endif

    /* The bottom info bar (TRIP/ODO/MAX/AVG/TIME) belonged to the removed Main page and was removed with it.
       Mileage statistics are still accumulated by a background task and can be shown on other pages or re-attached later. */

    /* ===== Video boot mode (INTRO == 2: VIDEO, the boot_block flashed via the phone app) ===== */
    // Moved to ui_ext.c; returns true while the Logo/video is still showing, so my_timerMain returns early.
    if (ui_ext_boot_video_tick()) return;

    /* ===== Boot flow / Showroom Intro playback (moved to ui_ext.c) ===== */
    ui_ext_intro_tick(is_slave);

    /* ---- RPM over-limit flash warning (migrated to ui_ext.c) ---- */
    ui_ext_rpm_flash_tick(rpm_for_warning, IN_SWEEP);

    if (!ui_ext_showroom_is_active()) {
        ui_ext_no_signal_update(ble_now);   // showroom mode is a fake-data demo, no NO SIGNAL hint
    }

    /* ---- Adaptive refresh rate: data pages run fast, static pages stay slow ----
       Only this UI timer's period changes (pure redraw pacing); no OBD/RS485/ESP-NOW query or broadcast is affected. */
    if (timer) {
        static uint32_t s_refresh_ms = 200;
        lv_obj_t *refresh_scr = lv_scr_act();
        uint32_t want_ms = ui_refresh_period_ms_for_screen(refresh_scr, IN_SWEEP, ui_ext_rpm_is_flashing(), ui_ext_rpm_link_ramp_active());
        if (want_ms != s_refresh_ms) {
            s_refresh_ms = want_ms;
            lv_timer_set_period(timer, want_ms);
        }
    }
    #undef IN_SWEEP
}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



///////////////////// FUNCTIONS ////////////////////
void ui_event_logo_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        static uint32_t last_click_tick = 0;
        static uint8_t  click_cnt = 0;
        uint32_t now = lv_tick_get();
        if(now - last_click_tick < 400){
            click_cnt++;
        }else{
            click_cnt = 1;
        }
        last_click_tick = now;

        if(click_cnt >= 2){
            click_cnt = 0;
            if(ui_ScreenPageODBProtocal == NULL) ui_ScreenPageODBProtocal_screen_init();
            lv_scr_load_anim(ui_ScreenPageODBProtocal, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, true);
            ui_ScreenPageLogo = NULL;
            imageLogo = NULL;
        }  

        ESP_LOGD(TAG, "Logo LV_EVENT_CLICKED");
    }   
}

#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
// Physical page buttons follow the same horizontal route as the touch carousel.
// Subpages return to their parent, just as a horizontal swipe does.
bool ui_stopwatch_button_navigate(bool next)
{
    lv_obj_t *screen = lv_scr_act();
#define BUTTON_GO(name) do { \
    _ui_screen_change(&ui_ScreenPage##name, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, \
                      &ui_ScreenPage##name##_screen_init); \
    return true; \
} while (0)

    if (screen == ui_ScreenPageGear)       { if (next) BUTTON_GO(Rpm); else BUTTON_GO(EasterEgg); }
    if (screen == ui_ScreenPageRpm)        { if (next) BUTTON_GO(Speed); else BUTTON_GO(Gear); }
    if (screen == ui_ScreenPageSpeed)      { if (next) BUTTON_GO(Temp); else BUTTON_GO(Rpm); }
    if (screen == ui_ScreenPageTemp)       { if (next) BUTTON_GO(Info); else BUTTON_GO(Speed); }
    if (screen == ui_ScreenPageInfo)       { if (next) BUTTON_GO(GForce); else BUTTON_GO(Temp); }
    if (screen == ui_ScreenPageGForce)     { if (next) BUTTON_GO(Needle); else BUTTON_GO(Info); }
    if (screen == ui_ScreenPageNeedle)     { if (next) BUTTON_GO(OilPressure); else BUTTON_GO(GForce); }
    if (screen == ui_ScreenPageEasterEgg) { if (next) BUTTON_GO(Gear); else BUTTON_GO(Expression); }
    if (screen == ui_ScreenPageExpression && next) BUTTON_GO(EasterEgg);
    if (screen == ui_ScreenPageOilPressure && !next) BUTTON_GO(Needle);

    // Optional theme pages sit between the chart and the final expression page.
    if (screen == ui_ScreenPageOilPressure || screen == ui_ScreenPageExpression) {
        uint8_t count = theme_page_list_count();
        if (count > 0) {
            ui_theme_gauge_page_index = next ? 0 : count - 1;
            if (ui_ScreenPageThemeGauge) {
                lv_obj_del(ui_ScreenPageThemeGauge);
                ui_ScreenPageThemeGauge = NULL;
            }
            BUTTON_GO(ThemeGauge);
        }
        if (next) BUTTON_GO(Expression); else BUTTON_GO(OilPressure);
    }
    if (screen == ui_ScreenPageThemeGauge) {
        uint8_t count = theme_page_list_count();
        if (next && ui_theme_gauge_page_index + 1 < count) {
            ++ui_theme_gauge_page_index;
        } else if (!next && ui_theme_gauge_page_index > 0) {
            --ui_theme_gauge_page_index;
        } else {
            if (next) BUTTON_GO(Expression); else BUTTON_GO(OilPressure);
        }
        lv_obj_t *old_theme_page = ui_ScreenPageThemeGauge;
        ui_ScreenPageThemeGauge = NULL;
        _ui_screen_change(&ui_ScreenPageThemeGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0,
                          &ui_ScreenPageThemeGauge_screen_init);
        // The active theme page is recreated for a different page index.
        // Release the old screen after loading its replacement.
        if (old_theme_page) lv_obj_del(old_theme_page);
        return true;
    }

    if (ui_settings_handle_back()) return true;
    if (screen == ui_ScreenPageGForceCal)  BUTTON_GO(GForce);
    if (screen == ui_ScreenPageRingSettings) BUTTON_GO(Settings);
    if (screen == ui_ScreenPageTempCustom) BUTTON_GO(Temp);
    if (screen == ui_ScreenPageInfoCustom) BUTTON_GO(Info);
    if (screen == ui_ScreenPageNeedleConfig) BUTTON_GO(Needle);
    if (screen == ui_ScreenPageChartConfig || screen == ui_ScreenPageChartAlarm ||
        screen == ui_ScreenPageOilWarn) BUTTON_GO(OilPressure);
    if (screen == ui_ScreenPageRpmWarn) BUTTON_GO(Rpm);
    if (screen == ui_ScreenPageSettings || screen == ui_ScreenPageODBProtocal) BUTTON_GO(EasterEgg);
    if (screen == ui_ScreenPageMultiGauge || screen == ui_ScreenPageFeedback || screen == ui_ScreenPageCxSettings) BUTTON_GO(Settings);
    if (screen == ui_ScreenPageBLEScan) {
        if (nvs_cfg_get()->device_role == ESPNOW_ROLE_SLAVE) gauge_pair_ble_scan_stop();
        else elm327_ble_scan_only_stop();
        BUTTON_GO(EasterEgg);
    }
#undef BUTTON_GO
    return false; // boot and OTA screens have their own controls
}

static bool ui_stopwatch_carousel_gesture(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_GESTURE) return false;
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    if (dir != LV_DIR_LEFT && dir != LV_DIR_RIGHT) return false;
    lv_indev_wait_release(lv_indev_get_act());
    return ui_stopwatch_button_navigate(dir == LV_DIR_LEFT);
}
#endif

// The Gear/RPM/Speed pages sit at the front of the carousel: Gear→RPM→Speed→Temp→… (swipe left = next / swipe right = previous)
// Swipe down from Gear enters the theme-provided gauge page (only if the active theme declares one).
void ui_event_gear_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM && theme_has_page("main_gauge")) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageThemeGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageThemeGauge_screen_init);
        }
    }
}

// Theme-provided gauge page: swipe left/right moves to the next/prev page
// declared by the active theme. Swiping left past the last theme page goes
// to the Info page (version/settings). Swiping right from the first theme
// page also goes to Info page (creating a loop: theme pages ↔ Info).
void ui_event_theme_gauge_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        uint8_t page_count = theme_page_list_count();

        if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_theme_gauge_page_index + 1 < page_count) {
                // Move to next theme page
                ui_theme_gauge_page_index++;
                ui_ScreenPageThemeGauge = NULL;  // Let _ui_screen_change delete the old screen
                _ui_screen_change(&ui_ScreenPageThemeGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageThemeGauge_screen_init);
            } else {
                // Past the last theme page → go to Info page (version/settings)
                _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
            }
        }
        else if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_theme_gauge_page_index > 0) {
                // Move to previous theme page
                ui_theme_gauge_page_index--;
                ui_ScreenPageThemeGauge = NULL;  // Let _ui_screen_change delete the old screen
                _ui_screen_change(&ui_ScreenPageThemeGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageThemeGauge_screen_init);
            } else {
                // Before the first theme page → go to Info page (creating a loop)
                _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
            }
        }
    }
}
void ui_event_rpm_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageGear, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGear_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSpeed, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSpeed_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpmWarn, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpmWarn_screen_init);
        }
    }
}
void ui_event_speed_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
    }
}
// Carousel order: Gear → RPM → Speed → Temp → Info → Needle → OilPressure → BrakeTemp → version page → back to Gear
// Swipe left = next page, swipe right = previous page
void ui_event_temp_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSpeed, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSpeed_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTempCustom, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTempCustom_screen_init);
        }
    }
}

void ui_event_temp_custom_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if (dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
    }
}

void ui_event_oil_pressure_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageNeedle, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedle_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            // the brake-temp page was merged into the chart page; swipe left goes to the next visible page in the ring (version page)
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            // swipe down → chart data-source selection page (delete the old instance to force a rebuild, reflecting the current data item/selection)
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_ScreenPageChartConfig) { lv_obj_del(ui_ScreenPageChartConfig); ui_ScreenPageChartConfig = NULL; }
            _ui_screen_change(&ui_ScreenPageChartConfig, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageChartConfig_screen_init);
        }
        else if(dir == LV_DIR_TOP) {
            // swipe up → alarm threshold settings page (delete the old instance to force a rebuild, per the current data item)
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_ScreenPageChartAlarm) { lv_obj_del(ui_ScreenPageChartAlarm); ui_ScreenPageChartAlarm = NULL; }
            _ui_screen_change(&ui_ScreenPageChartAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageChartAlarm_screen_init);
        }
    }
}

// Chart data-source selection page gestures: any direction returns to the chart page
void ui_event_chart_config_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
    }
}

// Chart alarm settings page gestures: any direction returns to the chart page
void ui_event_chart_alarm_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
    }
}

void ui_event_oil_warn_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
        }
    }
}

void ui_event_rpm_warn_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init);
        }
    }
}

// Needle page (gauge): sits between Info and OilPressure (before the two chart pages)
//  swipe right → Info, swipe left → OilPressure, swipe down → data-source selection
void ui_event_needle_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_BOTTOM){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageNeedleConfig, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedleConfig_screen_init);
        }
        else if(dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
            _ui_screen_change(&ui_ScreenPageExpression, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageExpression_screen_init);
#else
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
#endif
        }
        else if(dir == LV_DIR_LEFT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
        }
    }
}

// Needle config page: any direction returns to the needle page
void ui_event_needle_config_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageNeedle, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedle_screen_init);
    }
}

void ui_event_info_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
            _ui_screen_change(&ui_ScreenPageGForce, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGForce_screen_init);
#else
            _ui_screen_change(&ui_ScreenPageNeedle, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedle_screen_init);
#endif
        }
        else if(dir == LV_DIR_BOTTOM) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfoCustom, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfoCustom_screen_init);
        }
    }
}

void ui_event_gforce_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    if (lv_event_get_code(e) != LV_EVENT_GESTURE) return;
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    lv_indev_wait_release(lv_indev_get_act());
    if (dir == LV_DIR_RIGHT)
        _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
    else if (dir == LV_DIR_LEFT)
        _ui_screen_change(&ui_ScreenPageExpression, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageExpression_screen_init);
    else if (dir == LV_DIR_BOTTOM) {
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
        ui_settings_open_g_calibration(false);
#else
        _ui_screen_change(&ui_ScreenPageGForceCal, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGForceCal_screen_init);
#endif
    }
}

void ui_event_expression_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    if (lv_event_get_code(e) != LV_EVENT_GESTURE) return;
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    lv_indev_wait_release(lv_indev_get_act());
    if (dir == LV_DIR_RIGHT)
        _ui_screen_change(&ui_ScreenPageGForce, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGForce_screen_init);
    else if (dir == LV_DIR_LEFT)
        _ui_screen_change(&ui_ScreenPageNeedle, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedle_screen_init);
    else if (dir == LV_DIR_BOTTOM) {
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
        ui_settings_open_g_calibration(false);
#else
        _ui_screen_change(&ui_ScreenPageGForceCal, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGForceCal_screen_init);
#endif
    }
}

void ui_event_gforce_cal_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    ui_settings_detail_event(e);
#else
    if (lv_event_get_code(e) != LV_EVENT_GESTURE) return;
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_ScreenPageGForce, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGForce_screen_init);
#endif
}

void ui_event_info_custom_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if (dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
        }
    }
}
void ui_event_easter_egg_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (ui_stopwatch_carousel_gesture(e)) return;
#endif
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED && !ui_ext_showroom_is_active()) {
        ui_ext_showroom_handle_tap();  // 10 rapid taps on the version page enter showroom
        return;
    }
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT || dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            // If a custom theme with pages is loaded, swipe left/right returns to theme pages
            if (theme_page_list_count() > 0) {
                // Right swipe goes to last theme page, left swipe goes to first
                ui_theme_gauge_page_index = (dir == LV_DIR_RIGHT) ? (theme_page_list_count() - 1) : 0;
                if (ui_ScreenPageThemeGauge) {
                    lv_obj_del(ui_ScreenPageThemeGauge);
                    ui_ScreenPageThemeGauge = NULL;
                }
                _ui_screen_change(&ui_ScreenPageThemeGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageThemeGauge_screen_init);
            } else {
                // No theme loaded, return to Gear page
                _ui_screen_change(&ui_ScreenPageGear, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGear_screen_init);
            }
        }
        else if(dir == LV_DIR_TOP) {
#if !CONFIG_OBD_HW_VERSION_M5STOPWATCH
            // swipe up → BLE scan page
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageBLEScan, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageBLEScan_screen_init);
#endif
        }
        else if(dir == LV_DIR_BOTTOM) {
            // swipe down → settings page
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSettings, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSettings_screen_init);
        }
    }

    // ---- hand-written extension logic hook (ui_ext.c, not overwritten by SquareLine) ----
    ui_ext_tick();
}

// OTA button: enter OTA mode screen (WiFi SoftAP + HTTP server, no BLE)
void ui_event_easter_egg_ota_button(lv_event_t *e)
{
    (void)e;
    _ui_screen_change(&ui_ScreenPageOTAMode, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenPageOTAMode_screen_init);
}

// OTA mode screen: refresh status from the LVGL timer (called every 500ms)
void ui_ota_mode_refresh(void)
{
    if (ui_ScreenPageOTAMode == NULL) return;
    if (ui_LabelOTAModeStatus == NULL) return;

    if (ota_wifi_server_is_busy()) {
        lv_label_set_text(ui_LabelOTAModeStatus, "Receiving update...");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0x00CC66), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_READY) {
        lv_label_set_text(ui_LabelOTAModeStatus, "WiFi ready — connect your phone");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0x00CC66), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_IDLE) {
        lv_label_set_text(ui_LabelOTAModeStatus, "Starting WiFi...");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_ERROR) {
        lv_label_set_text(ui_LabelOTAModeStatus, "WiFi error");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    ui_peak_config_t peak_config = ui_peak_marker_config();
    ESP_LOGI("ui_peak", "Settings directory / white icons ready; peak marker %s / %upx / %us",
             peak_config.enabled ? "ON" : "OFF", peak_config.width_px, peak_config.lifetime_s);
#endif
    // OPTIMIZATION: Logo is already created and displayed by app_main.c before this function
    // to ensure both Master (with 2MB theme) and Slave show logo simultaneously.
    // Here we only load theme and create other UI elements.

    // Initialize theme partition system AFTER logo is visible
    // This loads the theme from theme_0/theme_1 partition, or falls back to default
    ESP_LOGI(TAG, "Initializing theme partition system");
    esp_err_t theme_ret = theme_engine_init();
    if (theme_ret == ESP_OK) {
        theme_info_t info;
        if (theme_get_info(&info) == ESP_OK) {
            ESP_LOGI(TAG, "Theme loaded: %s v%s by %s", info.name, info.version, info.author);
        }
        // Run test to print detailed theme info
        theme_engine_test();
    } else {
        ESP_LOGW(TAG, "Theme partition system initialization failed, using built-in themes");
    }

    // Load the saved UI theme BEFORE any screen is built, so every screen
    // picks up the active theme's colors at creation time.
    ui_theme_init();

    // MEMORY OPTIMIZATION: Conditionally create screens based on theme availability
    // If custom theme is loaded, skip built-in gauge pages (Gear/Rpm/Speed/Temp/Needle/OilPressure)
    // and rely on theme-provided pages instead. This saves ~40-60KB RAM for Master mode.
    bool has_custom_theme = false;
    theme_info_t theme_info;
    if (theme_get_info(&theme_info) == ESP_OK) {
        if (theme_info.id[0] != '\0' && strcmp(theme_info.id, "default") != 0) {
            has_custom_theme = true;
            ESP_LOGI(TAG, "Custom theme detected - skipping built-in gauge pages to save RAM");
        }
    }

    if (!has_custom_theme) {
        // No custom theme - create built-in gauge pages
        ui_ScreenPageGear_screen_init();
        ui_ScreenPageRpm_screen_init();
        ui_ScreenPageSpeed_screen_init();
        ui_ScreenPageTemp_screen_init();
        ui_ScreenPageOilPressure_screen_init();
        ui_ScreenPageNeedle_screen_init();
    } else {
        // Custom theme loaded - defer built-in gauge pages (only create if explicitly accessed)
        ui_ScreenPageGear = NULL;
        ui_ScreenPageRpm = NULL;
        ui_ScreenPageSpeed = NULL;
        ui_ScreenPageTemp = NULL;
        ui_ScreenPageOilPressure = NULL;
        ui_ScreenPageNeedle = NULL;
    }

    // System pages are always created (needed for settings/BLE/etc regardless of theme)
    ui_ScreenPageOilWarn_screen_init();
    ui_ScreenPageODBProtocal_screen_init();
    // The Info page is lazy-loaded on demand; its screen pointer must be initialized to NULL
    ui_ScreenPageInfo = NULL;
    ui_ScreenPageTempCustom = NULL;
    ui_ScreenPageInfoCustom = NULL;
    ui_ScreenPageNeedleConfig = NULL;   // config page lazy-loaded
    ui_ScreenPageMultiGauge = NULL;     // triple-gauge settings page lazy-loaded
    ui_ScreenPageChartConfig = NULL;    // chart data-source selection page lazy-loaded
    ui_ScreenPageChartAlarm = NULL;     // chart alarm settings page lazy-loaded
    ui_ScreenPageIntro = NULL;          // boot animation page lazy-loaded
    ui_ScreenPageThemeGauge = NULL;     // theme-provided gauge page, lazy-loaded (only reachable if the active theme declares "main_gauge")
    ui____initial_actions0 = lv_obj_create(NULL);

    // Pre-create the default boot page: build it before the boot switch so it isn't created synchronously mid-transition and cause a stutter.
    // The other default pages (Temp/Brake/OilP/Needle/Gear/Rpm/Speed) were eagerly created above; only Info is lazy-loaded.
    if (nvs_cfg_get()->default_page == 1 && ui_ScreenPageInfo == NULL) {
        ui_ScreenPageInfo_screen_init();
    }

    ui_data_entry_bind_timer(lv_timer_create(my_timerMain,
                    ui_refresh_period_ms_for_screen(lv_scr_act(), false, false, false),
                    NULL));
}

/* OBD protocol page events */
void ui_event_obd_prot_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
            if (dir == LV_DIR_LEFT) return;
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_settings_handle_back()) return;
#endif
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
    }else if(code == LV_EVENT_LONG_PRESSED){
        usSaveProtTimeCnt = 0;
    }else if(code == LV_EVENT_LONG_PRESSED_REPEAT){
        usSaveProtTimeCnt += 100; // this event fires every 100 ms
        if(usSaveProtTimeCnt >= SAVE_PROTOCOL_TIME){
            usSaveProtTimeCnt = 0;
            nvs_user_cfg_t cfg = *nvs_cfg_get();
            cfg.protocol = lv_roller_get_selected(ui_RollerODBProtocalChoose);
            nvs_cfg_set(&cfg);
            esp_restart();
        }
    }else if(code == LV_EVENT_RELEASED){
        usSaveProtTimeCnt = 0;
    }
}

/* BLE scan page events - swipe left returns to the device info page */
void ui_event_ble_scan_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    ui_settings_detail_event(e);
#else
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            // on this page slaves run the pairing scan (gauge_pair_ble), not the OBD scan (elm327_ble); stop the matching one when swiping away.
            if (nvs_cfg_get()->device_role == ESPNOW_ROLE_SLAVE) {
                gauge_pair_ble_scan_stop();
            } else {
                elm327_ble_scan_only_stop();
            }
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
    }
#endif
}

/* StopWatch settings use the visible directory; original boards keep their gestures. */
void ui_event_settings_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    ui_settings_detail_event(e);
#else
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM){   // swipe down enters the triple-gauge settings page
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageMultiGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageMultiGauge_screen_init);
        }
    }
#endif
}

void ui_event_feedback_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    ui_settings_detail_event(e);
#else
    if (lv_event_get_code(e) != LV_EVENT_GESTURE) return;
    lv_indev_wait_release(lv_indev_get_act());
    _ui_screen_change(&ui_ScreenPageSettings, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSettings_screen_init);
#endif
}

// Triple-gauge settings page gestures: swipe up/left/right → return to the settings page
void ui_event_multi_gauge_background(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    ui_settings_detail_event(e);
#else
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSettings, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSettings_screen_init);
        }
    }
#endif
}
