// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "ui_helpers.h"
#include "ui_theme.h"
#include "ui_status_ring.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "app_obd_dsp/vehicle_profiles.h"
#include "app_obd_dsp/project_identity.h"
#include <string.h>
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
#include "esp_heap_caps.h"
#include "stopwatch/stopwatch_board.h"
#endif

void _ui_bar_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
}

void _ui_basic_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
    if(id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
    if(id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
    if(id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}


void _ui_dropdown_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_DROPDOWN_PROPERTY_SELECTED) lv_dropdown_set_selected(target, val);
}

void _ui_image_set_property(lv_obj_t * target, int id, uint8_t * val)
{
    if(id == _UI_IMAGE_PROPERTY_IMAGE) lv_img_set_src(target, val);
}

void _ui_label_set_property(lv_obj_t * target, int id, const char * val)
{
    if(id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}


void _ui_roller_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM) lv_roller_set_selected(target, val, LV_ANIM_ON);
    if(id == _UI_ROLLER_PROPERTY_SELECTED) lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

void _ui_slider_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
}


void _ui_screen_change(lv_obj_t ** target, lv_scr_load_anim_t fademode, int spd, int delay, void (*target_init)(void))
{
    if(*target == NULL)
        target_init();
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (lv_scr_act() != *target)
        stopwatch_board_feedback(STOPWATCH_FEEDBACK_PAGE);
    // Carousel pages requested a 5 ms fade, shorter than the 16 ms display
    // refresh period. Skip the intermediate opacity frame and invalidate the
    // complete target screen in one pass; this also avoids retaining a
    // partially composited ring edge after a page switch.
    if (fademode == LV_SCR_LOAD_ANIM_FADE_ON && spd <= 5 && delay == 0) {
        lv_scr_load_anim(*target, LV_SCR_LOAD_ANIM_NONE, 0, 0, false);
        return;
    }
#endif
    lv_scr_load_anim(*target, fademode, spd, delay, false);
}

void _ui_arc_increment(lv_obj_t * target, int val)
{
    int old = lv_arc_get_value(target);
    lv_arc_set_value(target, old + val);
    lv_event_send(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_bar_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_bar_get_value(target);
    lv_bar_set_value(target, old + val, anm);
}

void _ui_slider_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_slider_get_value(target);
    lv_slider_set_value(target, old + val, anm);
    lv_event_send(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_keyboard_set_target(lv_obj_t * keyboard, lv_obj_t * textarea)
{
    lv_keyboard_set_textarea(keyboard, textarea);
}

void _ui_flag_modify(lv_obj_t * target, int32_t flag, int value)
{
    if(value == _UI_MODIFY_FLAG_TOGGLE) {
        if(lv_obj_has_flag(target, flag)) lv_obj_clear_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    }
    else if(value == _UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target, flag);
    else lv_obj_clear_flag(target, flag);
}
void _ui_state_modify(lv_obj_t * target, int32_t state, int value)
{
    if(value == _UI_MODIFY_STATE_TOGGLE) {
        if(lv_obj_has_state(target, state)) lv_obj_clear_state(target, state);
        else lv_obj_add_state(target, state);
    }
    else if(value == _UI_MODIFY_STATE_ADD) lv_obj_add_state(target, state);
    else lv_obj_clear_state(target, state);
}


void _ui_textarea_move_cursor(lv_obj_t * target, int val)

{

    if(val == UI_MOVE_CURSOR_UP) lv_textarea_cursor_up(target);
    if(val == UI_MOVE_CURSOR_RIGHT) lv_textarea_cursor_right(target);
    if(val == UI_MOVE_CURSOR_DOWN) lv_textarea_cursor_down(target);
    if(val == UI_MOVE_CURSOR_LEFT) lv_textarea_cursor_left(target);
    lv_obj_add_state(target, LV_STATE_FOCUSED);
}

void scr_unloaded_delete_cb(lv_event_t * e)

{

    lv_obj_t ** var = lv_event_get_user_data(e);
    lv_obj_del(*var);
    (*var) = NULL;

}

void _ui_opacity_set(lv_obj_t * target, int val)
{
    lv_obj_set_style_opa(target, val, 0);
}

void _ui_anim_callback_free_user_data(lv_anim_t * a)
{
    lv_mem_free(a->user_data);
    a->user_data = NULL;
}

void _ui_anim_callback_set_x(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_x(usr->target, v);

}


void _ui_anim_callback_set_y(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_y(usr->target, v);

}


void _ui_anim_callback_set_width(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_width(usr->target, v);

}


void _ui_anim_callback_set_height(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_height(usr->target, v);

}


void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_style_opa(usr->target, v, 0);

}


void _ui_anim_callback_set_image_zoom(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_img_set_zoom(usr->target, v);

}


void _ui_anim_callback_set_image_angle(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_img_set_angle(usr->target, v);

}


void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_img_set_src(usr->target, usr->imgset[v]);
}

int32_t _ui_anim_callback_get_x(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_x_aligned(usr->target);

}


int32_t _ui_anim_callback_get_y(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_y_aligned(usr->target);

}


int32_t _ui_anim_callback_get_width(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_width(usr->target);

}


int32_t _ui_anim_callback_get_height(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_height(usr->target);

}


int32_t _ui_anim_callback_get_opacity(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_style_opa(usr->target, 0);

}

int32_t _ui_anim_callback_get_image_zoom(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_img_get_zoom(usr->target);

}

int32_t _ui_anim_callback_get_image_angle(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_img_get_angle(usr->target);

}

int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;

}

void _ui_arc_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

void _ui_slider_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}
void _ui_checked_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)
{
    if(lv_obj_has_state(src, LV_STATE_CHECKED)) lv_label_set_text(trg, txt_on);
    else lv_label_set_text(trg, txt_off);
}


void _ui_spinbox_step(lv_obj_t * target, int val)

{

    if(val > 0) lv_spinbox_increment(target);

    else lv_spinbox_decrement(target);


    lv_event_send(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_switch_theme(int val)

{

#ifdef UI_THEME_ACTIVE
    ui_theme_set(val);
#endif
}

// ==================== Project-custom helpers (not SquareLine generated) ====================
// Hand-written style code repeated across multiple screens, extracted here for sharing.

// Outer bezel ring (360x360 on the original board, 456x456 on StopWatch).
// The original board retains its theme and each page's requested width;
// StopWatch uses one 10-pixel ring recolored by the current page's status.
// Callers keep their own lv_obj_move_foreground() after this.
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
#define STOPWATCH_RING_SIZE 456
#define STOPWATCH_RING_WIDTH 10

// LVGL's rounded rectangle border produces uneven coverage at a few angles
// on the 466-pixel AMOLED. Generate one symmetric alpha-only image instead;
// all pages share it and recolor it without regenerating the mask.
static lv_img_dsc_t s_stopwatch_ring_img;
#define STOPWATCH_RING_TILES 16
static lv_area_t s_ring_tiles[STOPWATCH_RING_TILES];
typedef struct {
    lv_obj_t obj;
    lv_color_t color;
    lv_opa_t opacity;
} stopwatch_ring_t;

static void stopwatch_ring_event(const lv_obj_class_t *class_p, lv_event_t *e)
{
    if(lv_obj_event_base(class_p, e) != LV_RES_OK) return;
    lv_obj_t *obj = lv_event_get_target(e);
    if(lv_event_get_code(e) == LV_EVENT_COVER_CHECK) {
        lv_cover_check_info_t *info = lv_event_get_param(e);
        info->res = LV_COVER_RES_NOT_COVER;
    } else if(lv_event_get_code(e) == LV_EVENT_DRAW_MAIN) {
        stopwatch_ring_t *ring = (stopwatch_ring_t *)obj;
        lv_draw_ctx_t *ctx = lv_event_get_draw_ctx(e);
        const lv_area_t *saved_clip = ctx->clip_area;
        lv_area_t coords; lv_obj_get_coords(obj, &coords);
        lv_draw_img_dsc_t dsc; lv_draw_img_dsc_init(&dsc);
        dsc.recolor = ring->color; dsc.recolor_opa = LV_OPA_COVER;
        dsc.opa = ring->opacity;
        for(unsigned i = 0; i < STOPWATCH_RING_TILES; ++i) {
            lv_area_t tile = s_ring_tiles[i], clipped;
            lv_area_move(&tile, coords.x1, coords.y1);
            if(!_lv_area_intersect(&clipped, saved_clip, &tile)) continue;
            ctx->clip_area = &clipped;
            lv_draw_img(ctx, &dsc, &coords, &s_stopwatch_ring_img);
        }
        ctx->clip_area = saved_clip;
    }
}
static const lv_obj_class_t stopwatch_ring_class = {
    .base_class = &lv_obj_class, .event_cb = stopwatch_ring_event,
    .instance_size = sizeof(stopwatch_ring_t)
};

static void ring_include_rotated_images(lv_obj_t *parent, lv_area_t *area)
{
    // LVGL's transformed-image sampling can differ by one color step when a
    // dirty rectangle cuts a glyph halfway across. Keep any intersecting
    // rotated glyph's whole draw footprint in the refresh rectangle.
    bool changed;
    do {
        changed = false;
        for(uint32_t i = 0; i < lv_obj_get_child_cnt(parent); ++i) {
            lv_obj_t *child = lv_obj_get_child(parent, i);
            if(lv_obj_has_flag(child, LV_OBJ_FLAG_HIDDEN) ||
               !lv_obj_has_class(child, &lv_img_class) ||
               (!lv_img_get_angle(child) && lv_img_get_zoom(child) == LV_IMG_ZOOM_NONE)) continue;
            lv_area_t bounds, overlap, expanded;
            lv_obj_get_coords(child, &bounds);
            lv_coord_t extra = _lv_obj_get_ext_draw_size(child);
            bounds.x1 -= extra; bounds.x2 += extra;
            bounds.y1 -= extra; bounds.y2 += extra;
            if(!_lv_area_intersect(&overlap, area, &bounds)) continue;
            _lv_area_join(&expanded, area, &bounds);
            if(memcmp(area, &expanded, sizeof(expanded))) { *area = expanded; changed = true; }
        }
    } while(changed);
}

static bool stopwatch_ring_mask_init(void)
{
    if(s_stopwatch_ring_img.data) return true;
    const size_t size = STOPWATCH_RING_SIZE * STOPWATCH_RING_SIZE;
    uint8_t *mask = heap_caps_malloc(size, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if(!mask) return false;

    const float center = STOPWATCH_RING_SIZE / 2.0f;
    const float outer = (STOPWATCH_RING_SIZE - 1) / 2.0f;
    const float inner = outer - STOPWATCH_RING_WIDTH;
    const float outer_empty_sq = (outer + 1.0f) * (outer + 1.0f);
    const float outer_full_sq = (outer - 1.0f) * (outer - 1.0f);
    const float inner_empty_sq = (inner - 1.0f) * (inner - 1.0f);
    const float inner_full_sq = (inner + 1.0f) * (inner + 1.0f);
    const float outer_sq = outer * outer;
    const float inner_sq = inner * inner;

    for(int y = 0; y < STOPWATCH_RING_SIZE; ++y) {
        const float dy = y + 0.5f - center;
        for(int x = 0; x < STOPWATCH_RING_SIZE; ++x) {
            const float dx = x + 0.5f - center;
            const float d_sq = dx * dx + dy * dy;
            uint8_t alpha = 0;
            if(d_sq >= inner_full_sq && d_sq <= outer_full_sq) {
                alpha = 255;
            } else if(d_sq >= inner_empty_sq && d_sq <= outer_empty_sq) {
                // Supersample only the two edges, so their pixel coverage is
                // smooth and identical in every quadrant without an arc seam.
                int covered = 0;
                for(int sy = 0; sy < 4; ++sy) {
                    const float sample_y = dy + (sy - 1.5f) * 0.25f;
                    for(int sx = 0; sx < 4; ++sx) {
                        const float sample_x = dx + (sx - 1.5f) * 0.25f;
                        const float sample_sq = sample_x * sample_x + sample_y * sample_y;
                        if(sample_sq >= inner_sq && sample_sq <= outer_sq) ++covered;
                    }
                }
                alpha = (covered * 255 + 8) / 16;
            }
            mask[y * STOPWATCH_RING_SIZE + x] = alpha;
        }
    }

    s_stopwatch_ring_img.header.always_zero = 0;
    s_stopwatch_ring_img.header.w = STOPWATCH_RING_SIZE;
    s_stopwatch_ring_img.header.h = STOPWATCH_RING_SIZE;
    s_stopwatch_ring_img.header.cf = LV_IMG_CF_ALPHA_8BIT;
    s_stopwatch_ring_img.data_size = size;
    s_stopwatch_ring_img.data = mask;
    // Two half-circle tiles for each of eight horizontal bands. Sixteen
    // invalid rectangles leave room for moving dots/labels in LVGL's queue.
    // Their bounds come from the SAME smooth mask, so no geometry changes.
    for(unsigned i = 0; i < STOPWATCH_RING_TILES; ++i) {
        int band = i / 2, half = i % 2;
        lv_area_t *a = &s_ring_tiles[i];
        *a = (lv_area_t){STOPWATCH_RING_SIZE, STOPWATCH_RING_SIZE, -1, -1};
        for(int y = band * STOPWATCH_RING_SIZE / 8; y < (band + 1) * STOPWATCH_RING_SIZE / 8; ++y)
            for(int x = half * STOPWATCH_RING_SIZE / 2; x < (half + 1) * STOPWATCH_RING_SIZE / 2; ++x)
                if(mask[y * STOPWATCH_RING_SIZE + x]) {
                    if(x < a->x1) a->x1 = x;
                    if(y < a->y1) a->y1 = y;
                    if(x > a->x2) a->x2 = x;
                    if(y > a->y2) a->y2 = y;
                }
    }
    return true;
}
#endif

bool ui_helpers_set_ring_color(lv_obj_t *obj, lv_color_t color, lv_opa_t opacity)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if(lv_obj_check_type(obj, &stopwatch_ring_class)) {
        stopwatch_ring_t *ring = (stopwatch_ring_t *)obj;
        if(ring->color.full == color.full && ring->opacity == opacity) return true;
        ring->color = color; ring->opacity = opacity;
        lv_area_t coords; lv_obj_get_coords(obj, &coords);
        for(unsigned i = 0; i < STOPWATCH_RING_TILES; ++i) {
            lv_area_t tile = s_ring_tiles[i];
            lv_area_move(&tile, coords.x1, coords.y1);
            ring_include_rotated_images(lv_obj_get_parent(obj), &tile);
            lv_obj_invalidate_area(obj, &tile);
        }
        return true;
    }
#else
    (void)obj; (void)color; (void)opacity;
#endif
    return false;
}

lv_obj_t * ui_helpers_create_ring(lv_obj_t * parent, uint8_t border_width)
{
#if !CONFIG_OBD_HW_VERSION_M5STOPWATCH
    const ui_theme_t *th = ui_theme_active();
    // Themed bezel artwork: any shape (notches, tick marks, gradients) instead
    // of the plain circle border. Colors are baked into the artwork.
    if(th->ring_img) {
        lv_obj_t *ring = lv_img_create(parent);
        lv_img_set_src(ring, th->ring_img);
        lv_obj_set_align(ring, LV_ALIGN_CENTER);
        lv_obj_clear_flag(ring, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
        ui_status_ring_register(parent, ring, true);
        return ring;
    }
#endif

#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if(stopwatch_ring_mask_init()) {
        lv_obj_t *ring = lv_obj_class_create_obj(&stopwatch_ring_class, parent);
        lv_obj_class_init_obj(ring);
        lv_obj_remove_style_all(ring);
        lv_obj_set_size(ring, STOPWATCH_RING_SIZE, STOPWATCH_RING_SIZE);
        lv_obj_set_align(ring, LV_ALIGN_CENTER);
        ((stopwatch_ring_t *)ring)->color = ui_theme_color_lv(UI_COLOR_RING);
        ((stopwatch_ring_t *)ring)->opacity = LV_OPA_COVER;
        lv_obj_clear_flag(ring, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
        ui_status_ring_register(parent, ring, false);
        return ring;
    }
#endif

    lv_obj_t *ring = lv_obj_create(parent);
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    lv_obj_set_size(ring, STOPWATCH_RING_SIZE, STOPWATCH_RING_SIZE);
    border_width = STOPWATCH_RING_WIDTH;
#else
    lv_obj_set_size(ring, 360, 360);
#endif
    lv_obj_set_align(ring, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ring, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ring, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ring, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(ring, 0, LV_PART_MAIN);
    lv_obj_set_style_border_color(ring, ui_theme_color_lv(UI_COLOR_RING), LV_PART_MAIN);
    lv_obj_set_style_border_width(ring, border_width, LV_PART_MAIN);
    lv_obj_set_style_border_opa(ring, 255, LV_PART_MAIN);
    ui_status_ring_register(parent, ring, false);
    return ring;
}

#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
LV_IMG_DECLARE(ui_img_mini_jcw);
LV_IMG_DECLARE(ui_img_mini_gp3);

static bool vehicle_is_gp3(void)
{
    return strcmp(vehicle_profile_get_active()->name, "GP3 F56 8AT") == 0;
}

static bool vehicle_is_jcw(void)
{
    return strcmp(vehicle_profile_get_active()->name, "JCW F56 8AT") == 0;
}
#endif

lv_color_t ui_helpers_brand_accent_color(void)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (vehicle_is_gp3()) return lv_color_hex(0xE62E27);
#endif
    return lv_color_hex(0xF05A28);
}

lv_obj_t * ui_helpers_create_mini_brand(lv_obj_t *parent, lv_coord_t center_y, bool large)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (vehicle_is_gp3() || vehicle_is_jcw()) {
        lv_obj_t *logo = lv_img_create(parent);
        lv_img_set_src(logo, vehicle_is_gp3() ? &ui_img_mini_gp3 : &ui_img_mini_jcw);
        lv_img_set_zoom(logo, large ? 256 : 128);
        lv_obj_align(logo, LV_ALIGN_CENTER, 0, center_y);
        lv_obj_clear_flag(logo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
        return logo;
    }
#endif
    // Other vehicle profiles have no MINI identity. Use the project name.
    lv_obj_t *label = lv_label_create(parent);
    lv_label_set_text(label, OBD_PROJECT_NAME);
    lv_obj_set_style_text_font(label, large ? &ui_font_FontTypoderSize36 : &ui_font_FontTypoderSize16, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, ui_theme_color_lv(UI_COLOR_TEXT_PRIMARY), LV_PART_MAIN);
    lv_obj_align(label, LV_ALIGN_CENTER, 0, center_y);
    lv_obj_clear_flag(label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    return label;
}

void ui_helpers_style_screen_bg(lv_obj_t * scr)
{
    const ui_theme_t *th = ui_theme_active();
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    // The panel has its own round mask. A rounded LVGL root leaves a thin
    // antialiased seam at the edge and does not clear pixels outside it when
    // changing pages. Paint the full square canvas black instead.
    lv_obj_set_style_radius(scr, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(scr, 0, LV_PART_MAIN);
    lv_obj_set_style_outline_width(scr, 0, LV_PART_MAIN);
#endif
    lv_obj_set_style_bg_color(scr, ui_theme_color_lv(UI_COLOR_BG),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    // Always assign, NULL included: screens are reused and the RPM warning
    // swaps the background image out, so it must be able to swap back.
    lv_obj_set_style_bg_img_src(scr, th->dial_face, LV_PART_MAIN | LV_STATE_DEFAULT);
}

// Dark roller shared colors/border/rounded corners (selected state: black text on white); caller only passes the font.
// Structural settings (width/visible rows/gesture blocking, etc.) vary per page and stay with the caller.
static void option_feedback_event(lv_event_t * e)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    if (lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED)
        stopwatch_board_feedback(STOPWATCH_FEEDBACK_OPTION);
#else
    (void)e;
#endif
}

void ui_helpers_enable_option_feedback(lv_obj_t * obj)
{
#if CONFIG_OBD_HW_VERSION_M5STOPWATCH
    lv_obj_add_event_cb(obj, option_feedback_event, LV_EVENT_VALUE_CHANGED, NULL);
#else
    (void)obj;
#endif
}

void ui_helpers_style_dark_roller(lv_obj_t * r, const lv_font_t * font)
{
    lv_obj_set_style_text_font(r, font, LV_PART_MAIN);
    lv_obj_set_style_text_color(r, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_bg_color(r, lv_color_hex(0x222222), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(r, 255, LV_PART_MAIN);
    lv_obj_set_style_border_width(r, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(r, lv_color_hex(0x444444), LV_PART_MAIN);
    lv_obj_set_style_radius(r, 8, LV_PART_MAIN);
    lv_obj_set_style_text_font(r, font, LV_PART_SELECTED);
    lv_obj_set_style_text_color(r, lv_color_hex(0x000000), LV_PART_SELECTED);
    lv_obj_set_style_bg_color(r, lv_color_hex(0xFFFFFF), LV_PART_SELECTED);
    lv_obj_set_style_bg_opa(r, 255, LV_PART_SELECTED);
    ui_helpers_enable_option_feedback(r);
}
