"""Make the 90 px RPM font from the checked-in 140 px Conthrax glyph atlas.

Requires Pillow only when regenerating. The generated C file is built normally
by ESP-IDF; no font tool or Pillow dependency is added to firmware builds.
"""
from pathlib import Path
import re
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "main/export_path/fonts/ui_font_FontTypoderSize140.c"
TARGET = ROOT / "main/export_path/fonts/ui_font_FontTypoderSize90.c"
SCALE = 90 / 140


def scaled(value):
    return round(int(value) * SCALE)


def main():
    source = SOURCE.read_text(encoding="utf-8")
    bitmap_match = re.search(r"(static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap\[\] = \{)(.*?)(\n\};)", source, re.S)
    if not bitmap_match:
        raise ValueError("Expected the uncompressed 4 bpp source atlas")
    raw = bytes(int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]+)", bitmap_match[2]))
    descriptor_match = re.search(r"(static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc\[\] = \{)(.*?)(\n\};)", source, re.S)
    glyphs = [dict((key, int(value)) for key, value in re.findall(r"\.(\w+)\s*=\s*(-?\d+)", entry))
              for entry in re.findall(r"\{([^{}]+)\}", descriptor_match[2])]
    packed = bytearray()
    descriptors = []
    for glyph in glyphs:
        old_w, old_h, offset = glyph['box_w'], glyph['box_h'], glyph['bitmap_index']
        new_w, new_h = scaled(old_w), scaled(old_h)
        new = {'bitmap_index': len(packed), 'adv_w': scaled(glyph['adv_w']),
               'box_w': new_w, 'box_h': new_h,
               'ofs_x': scaled(glyph['ofs_x']), 'ofs_y': scaled(glyph['ofs_y'])}
        descriptors.append("    {" + ", ".join(f".{key} = {value}" for key, value in new.items()) + "}")
        if old_w and old_h:
            pixels = bytes(((raw[offset+i//2] >> (4 if i%2 == 0 else 0)) & 15) * 17
                           for i in range(old_w * old_h))
            image = Image.frombytes("L", (old_w, old_h), pixels)
            image = image.resize((new_w, new_h), Image.Resampling.LANCZOS)
            levels = [min(15, max(0, round(value/17))) for value in image.tobytes()]
            for i in range(0, len(levels), 2):
                packed.append((levels[i] << 4) | (levels[i+1] if i+1 < len(levels) else 0))
    bitmap_text = "\n" + "\n".join("    " + ", ".join(f"0x{value:02x}" for value in packed[i:i+16]) + ","
                                     for i in range(0, len(packed), 16))
    output = source[:bitmap_match.start(2)] + bitmap_text + source[bitmap_match.end(2):]
    output = re.sub(r"(static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc\[\] = \{).*?(\n\};)",
                    lambda match: match[1]+"\n"+",\n".join(descriptors)+match[2], output, flags=re.S)
    output = re.sub(r"(static const int8_t kern_pair_values\[\] =\s*\{)(.*?)(\n\};)",
                    lambda match: match[1]+"\n    "+", ".join(str(scaled(value)) for value in re.findall(r"-?\d+", match[2]))+match[3],
                    output, flags=re.S)
    for field in ('line_height', 'base_line', 'underline_position', 'underline_thickness'):
        output = re.sub(rf"(\.{field}\s*=\s*)(-?\d+)", lambda match: match[1]+str(scaled(match[2])), output)
    output = output.replace('FontTypoderSize140', 'FontTypoderSize90').replace('FONTTYPODERSIZE140', 'FONTTYPODERSIZE90')
    output = re.sub(r"\A/\*.*?\*/", "/* Generated by tools/make_rpm_font.py from the checked-in 140 px Conthrax\n"
                    " * atlas. 90 px, uncompressed 4 bpp; glyphs and kerning use the same scale.\n"
                    " * Used by the StopWatch RPM readout to fit inside its progress arc. */", output, count=1, flags=re.S)
    TARGET.write_text(output, encoding="utf-8", newline="\n")
    print(f"{TARGET}: {len(packed)} bitmap bytes, {len(glyphs)} glyph descriptors")


if __name__ == '__main__':
    main()
